#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerMarketApp.Views.Home
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Search.cshtml")]
    public partial class Search : System.Web.Mvc.WebViewPage<FarmerMarketApp.Models.SearchInput>
    {
        public Search()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Home\Search.cshtml"
  
    ViewBag.Title = "Search";

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 90), Tuple.Create("\"", 125)
, Tuple.Create(Tuple.Create("", 96), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-1.9.1.min.js")
, 96), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 145), Tuple.Create("\"", 179)
, Tuple.Create(Tuple.Create("", 151), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/modernizr-2.6.2.js")
, 151), false)
);

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    $(function () {
        if (!Modernizr.geolocation) {
            alert(""This browser doesn't support the Geolocation API."");
        } else {
            // alert(""This browser does support the Geolocation API."");
            navigator.geolocation.getCurrentPosition(GotLocation, FailedLocation);
        }
    });

    function GotLocation(position) {
        var curLatitude = position.coords.latitude;
        var curLongitude = position.coords.longitude;
        // alert(""Lat: "" + curLatitude + "" Long: "" + curLongitude);
        $('#longitudeTextBox').val(curLongitude);
        $('#latitudeTextBox').val(curLatitude);
    }

    function FailedLocation() {
        alert(""Failed to get the location."");
    }
</script>

<h2>Search</h2>

");

            
            #line 33 "..\..\Views\Home\Search.cshtml"
 using (Html.BeginForm()) { 

            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend>Find a Farmer\'s Market Near You!</legend>\r\n      " +
"  <table>\r\n            <tr>\r\n                <td>");

            
            #line 38 "..\..\Views\Home\Search.cshtml"
               Write(Html.LabelFor(model => model.x));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 39 "..\..\Views\Home\Search.cshtml"
               Write(Html.TextBoxFor(model => model.x, new { @id = "longitudeTextBox" }));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 40 "..\..\Views\Home\Search.cshtml"
               Write(Html.ValidationMessageFor(model => model.x));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n            <tr>\r\n                <td>");

            
            #line 43 "..\..\Views\Home\Search.cshtml"
               Write(Html.LabelFor(model => model.y));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 44 "..\..\Views\Home\Search.cshtml"
               Write(Html.TextBoxFor(model => model.y, new { @id = "latitudeTextBox" }));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 45 "..\..\Views\Home\Search.cshtml"
               Write(Html.ValidationMessageFor(model => model.y));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n            <tr>\r\n                <td>");

            
            #line 48 "..\..\Views\Home\Search.cshtml"
               Write(Html.LabelFor(model => model.distance));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 49 "..\..\Views\Home\Search.cshtml"
               Write(Html.TextBoxFor(model => model.distance));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 50 "..\..\Views\Home\Search.cshtml"
               Write(Html.ValidationMessageFor(model => model.distance));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n            <tr>\r\n                <td><input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" name=\"Submit\"");

WriteLiteral(" /></td>\r\n            </tr>\r\n        </table>\r\n    </fieldset>\r\n");

            
            #line 57 "..\..\Views\Home\Search.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("<h3");

WriteLiteral(" class=\"LongTest\"");

WriteLiteral("></h3>");

        }
    }
}
#pragma warning restore 1591
