//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerMarketApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class FarmerMarket
    {
        public double FMID { get; set; }
        public string MarketName { get; set; }
        public string Website { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public Nullable<double> Zip { get; set; }
        public string Schedule { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public string Location { get; set; }
        public string Credit { get; set; }
        public string WIC { get; set; }
        public string WICcash { get; set; }
        public string SFMNP { get; set; }
        public string SNAP { get; set; }
        public string Bakedgoods { get; set; }
        public string Cheese { get; set; }
        public string Crafts { get; set; }
        public string Flowers { get; set; }
        public string Eggs { get; set; }
        public string Seafood { get; set; }
        public string Herbs { get; set; }
        public string Vegetables { get; set; }
        public string Honey { get; set; }
        public string Jams { get; set; }
        public string Maple { get; set; }
        public string Meat { get; set; }
        public string Nursery { get; set; }
        public string Nuts { get; set; }
        public string Plants { get; set; }
        public string Poultry { get; set; }
        public string Prepared { get; set; }
        public string Soap { get; set; }
        public string Trees { get; set; }
        public string Wine { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public int Id { get; set; }
        public System.Data.Spatial.DbGeography GeoLocation { get; set; }
    }
}
